volumes:
  minio_data:
    external: false
  postgres_data:
    external: false
  registry_data:
    external: false
  remark42_data:
    external: false
  neo4j_data:
    external: false
  neo4j_logs:
    external: false
  neo4j_import:
    external: false
  neo4j_plugins:
    external: false

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=accelerator
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d accelerator" ]
      interval: 5s
      timeout: 3s
      retries: 5

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
      - "${MINIO_DEV_CERT_LOCATION:?err}:/root/.minio/certs"
    env_file:
      - ./.env.minio

  #web_be:
  #  build:
  #    context: "${PROJECT_FOLDER:?err}"
  #    dockerfile: dockerfiles/Dockerfile.be
  #  volumes:
  #    - "${PROJECT_FOLDER:?err}:/app/"
  #  ports:
  #    - 8000:8000
  #    - 20102:20102
  #    - 5173:5173
  #  env_file:
  #    - ./.env.web.be
  #  stdin_open: true
  #  tty: true
  #  depends_on:
  #    db:
  #      condition: service_healthy
  #    minio:
  #      condition: service_started
  #    redis:
  #      condition: service_healthy

  web_be:
    build:
      context: "${PROJECT_FOLDER:?err}"
      dockerfile: dockerfiles/Dockerfile.devc
    volumes:
      - "${PROJECT_FOLDER:?err}:/app/"
      - ../../xet-core:/app/xet-core
      - ../xet_shard_parser:/app/xet_shard_parser
      - ../../hf-mount:/app/hf-mount
      - ../../hf-csi-driver:/app/hf-csi-driver
      - ${ACLI_PROJECT_FOLDER:?err}:/app/accli
      - ${WKUBE_JOB_AGENT_PROJECT_FOLDER:?err}:/app/wkube_job_agent
      - ${WKUBE_JOB_GATEWAY_INTERACTIVE_PROJECT_FOLDER:?err}:/app/wkube_job_gateway_interactive

    ports:
      - 8000:8000
      - 20102:20102
      - 8081:8081
      - 8080:8080
      - 5173:5173
    env_file:
      - ./.env.web.be
      - ./.env.web.fe
    stdin_open: true
    tty: true
    privileged: true
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
      redis:
        condition: service_started

  recon:
    build:
      context: "${PROJECT_FOLDER:?err}"
      dockerfile: dockerfiles/Dockerfile.recon
    ports:
      - 8900:8900
    env_file:
      - ./.env.web.be

    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
      redis:
        condition: service_started

  xet-janitor:
    build:
      context: "${PROJECT_FOLDER:?err}"
      dockerfile: dockerfiles/Dockerfile.devc
    #      dockerfile: dockerfiles/Dockerfile.be
    volumes:
      - "${PROJECT_FOLDER:?err}:/app/"
    env_file:
      - ./.env.web.be
    stdin_open: true
    command: celery -A xet_janitor.celery_app worker --loglevel=info -Q janitor_queue -B
    tty: true
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
      redis:
        condition: service_started

  titiler:
    build:
      context: "${TITILER_FOLDER:?err}"
      dockerfile: Dockerfile.dev
    platform: linux/x86_64
    ports:
      - 8002:8000
    volumes:
      - "${TITILER_FOLDER:?err}:/app/"
    environment:
      - TITILER_API_CORS_ORIGINS=https://localhost:8080,http://localhost:8080,https://accelerator.iiasa.ac.at,https://141-iiasa-forestnavigator.vercel.app

  acli:
    build:
      context: "${ACLI_PROJECT_FOLDER:?err}"
      dockerfile: Dockerfile.dev
    command: sleep infinity
    privileged: true
    volumes:
      - "${ACLI_PROJECT_FOLDER:?err}:/app/"

  scheduler:
    build:
      context: "${PROJECT_FOLDER:?err}"
      dockerfile: dockerfiles/Dockerfile.scheduler
    # command: sleep infinity
    privileged: true
    env_file:
      - ./.env.web.be
    # volumes:
    #   - "${PROJECT_FOLDER:?err}:/home/ubuntu/app/"
    depends_on:
      web_be:
        condition: service_started
      redis:
        condition: service_started
      registry:
        condition: service_started

  k8s_events:
    build:
      context: "${SCHEDULER_PROJECT_FOLDER:?err}"
      dockerfile: dockerfiles/Dockerfile.k8s.events.dev
    env_file:
      - ./.env.scheduler
    volumes:
      - "${SCHEDULER_PROJECT_FOLDER:?err}:/app/"
    depends_on:
      web_be:
        condition: service_started

  # accms:
  #   build:
  #     context: "${ACCMS_PROJECT_FOLDER:?err}"
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - 8001:8000
  #   env_file:
  #     - ./.env.accms
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - "${ACCMS_PROJECT_FOLDER:?err}:/app/"
  #   depends_on:
  #     db:
  #       condition: service_healthy

  # threads:
  #   build:
  #     context: "${THREADS_PROJECT_FOLDER:?err}"
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - 8003:8000
  #   env_file:
  #     - ./.env.threads
  #   volumes:
  #     - "${THREADS_PROJECT_FOLDER:?err}:/app/"
  #   depends_on:
  #     db:
  #       condition: service_healthy

  registry:
    image: registry:2
    ports:
      - "5000:5000"
      - "8443:8443"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_HTTP_ADDR: registry:8443
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/server.crt
      REGISTRY_HTTP_TLS_KEY: /certs/server.key
    # Way to generate htpasswd file
    # docker run --rm --entrypoint htpasswd httpd:2 -Bbn myregistry myregistrypassword > services_docker_compose_for_dev/registry_auth/htpasswd
    volumes:
      - registry_data:/var/lib/registry
      - ./registry_auth:/auth
      - ./registry_certs:/certs

  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=myredispassword
      - REDIS_MAXMEMORY=1536mb
      - REDIS_MAXMEMORY_POLICY=noeviction
    deploy:
      resources:
        limits:
          memory: 2G
