apiVersion: v1
kind: Secret
metadata:
  name: accelerator-be-secret
type: Opaque
stringData:
  DEBUG_MODE: '1'
  IIASA_MICROSOFT_OPENID_ISSUER_WELL_KNOWN_CONF: 'https://login.microsoftonline.com/9b79b10b-0007-4e8a-b072-ad0c8cdc1aa5/v2.0/.well-known/openid-configuration'
  BUCKET_DETAILS_ENCRYPTION_KEY: 'BXFQ....EE2L44XP4='
  JWT_BASE64_PRIVATE_KEY: 'LS0tLS1C....S0tLQo='
  JWT_BASE64_PUBLIC_KEY: 'LS0t....'
  ALLOWED_ORIGINS: '["http://accelerator.iiasa.ac.at","https://accelerator.iiasa.ac.at","http://sandbox.accelerator.iiasa.ac.at","https://sandbox.accelerator.iiasa.ac.at","https://141-iiasa-forestnavigator.vercel.app","https://141-iiasa-forest.vercel.app", "https://localhost:7979", "https://fn-portal.iiasa.ac.at", "https://fn-portal-dev.iiasa.ac.at", "https://fn-portal-staging.iiasa.ac.at", "https://iiasa.github.io"]'
  DATABASE_URL: 'postgresql://accelerator_prod:password222@142.121.81.21:5432/accelerator_p'

  INITIAL_S3_ENDPOINT: 'https://minio81.iiasa.ac.at:9000'
  INITIAL_S3_API_KEY: 'ac_accelerator_prod'
  INITIAL_S3_SECRET_KEY: 'Izlwa'
  INITIAL_S3_BUCKET_NAME: 'accelerator-p'

  REFRESH_TOKEN_SECRET_KEY: 'K7....kLt'

  XET_CAS_S3_ENDPOINT_INTERNAL: 'https://hctr1.iiasa.ac.at'
  XET_CAS_S3_ENDPOINT: 'https://1s3.iiasa.ac.at'
  XET_CAS_S3_API_KEY: 'asdfgasdgasg'
  XET_CAS_S3_SECRET_KEY: 'fdhgfdhgf'
  XET_CAS_S3_BUCKET_NAME: 's3-accelerator'

  XET_REDIS_URL: 'redis://:myredispass@redis:6379/0'


  CELERY_BROKER_URL: 'redis://:myredispass@redis:6379/1'
  SMTP_HOST: 'dzsm1.iiasa.ac.at'
  SMTP_PORT: '25'
  SMTP_STARTTLS: '0'
  SMTP_AUTH_REQUIRED: '0'
  ACCELERATOR_EMAIL: 'accelerator@iiasa.ac.at'
  FRONTEND_URL: 'https://accelerator.iiasa.ac.at'
  JOB_SECRET_ENCRYPTION_KEY: 'yrYyAVWYXw='
  JOBSTORE_S3_ENDPOINT: 'https://s3asdf.iiasa.ac.at'
  JOBSTORE_S3_ENDPOINT_INTERNAL: 'https://minio81.iiasa.ac.at:9000'
  JOBSTORE_S3_API_KEY: 'ac_accelerator_uaasdfat'
  JOBSTORE_S3_SECRET_KEY: 'ia5xsUGh'
  JOBSTORE_S3_BUCKET_NAME: 'accelerator-tasfd'
  SENTRY_DSN: 'https://9a41371.ingest.us.sentry.io/4509709034258432'
  OPENAI_API_KEY: 'sk-scPZyhj3uWMI2e45s9KkBJlRsA'
  OPENAI_API_BASE: 'https://api.openai.com/v1'
  GCP_SERVICE_ACCOUNT_BASE64_JSON: 'ewogI..'
  GCP_LOCATION: 'us-central1'

  TEAMS_WEBHOOK_URL: '<webhool_url>'
  RECON_APP_BASE_URL: 'https://recon.iiasa.ac.at'

  ACCELERATOR_CLI_BASE_URL: 'http://hgf1021:30106'
  IMAGE_REGISTRY_URL: 'imgstr.iiasa.ac.at'
  IMAGE_REGISTRY_TAG_PREFIX: 'acc/'
  IMAGE_REGISTRY_USER: 'accelerator'
  IMAGE_REGISTRY_PASSWORD: 'registry_password'
  OCI_BUILDER_IMAGE: 'img.iiasa.ac.at/acc/wk-image-builder:04044b09'
  
  # Required for wkube image builder, wkube task dispacher and k8 event worker
  WKUBE_K8_NAMESPACE: 'wkube'
  WKUBE_SECRET_JSON_B64: 'esdasf=='


  WKUBE_WORKFLOW_STORAGE_CLASS: 'local-path'
  
  ACCELERATOR_APP_TOKEN: 'eyk8yQ'
  TUNNEL_GATEWAY_SSH_PRIVATE_KEY_BASE64: 'LS0S0VZLS0tLS0K'



